package com.hbird.base.mvp.model.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hbird.base.mvc.bean.WaterOrderBean;
import com.hbird.base.mvp.model.entity.table.HbirdIncomeType;
import com.hbird.base.mvp.model.entity.table.HbirdSpendType;
import com.hbird.base.mvp.model.entity.table.HbirdUserCommTypePriority;
import com.hbird.base.mvp.model.entity.table.HbirdUserCommUseIncome;
import com.hbird.base.mvp.model.entity.table.HbirdUserCommUseSpend;
import com.hbird.base.mvp.model.entity.table.MovieCollect;
import com.hbird.base.mvp.model.entity.table.WaterOrderCollect;

import com.hbird.base.mvp.model.db.greendao.WaterOrderBeanDao;
import com.hbird.base.mvp.model.db.greendao.HbirdIncomeTypeDao;
import com.hbird.base.mvp.model.db.greendao.HbirdSpendTypeDao;
import com.hbird.base.mvp.model.db.greendao.HbirdUserCommTypePriorityDao;
import com.hbird.base.mvp.model.db.greendao.HbirdUserCommUseIncomeDao;
import com.hbird.base.mvp.model.db.greendao.HbirdUserCommUseSpendDao;
import com.hbird.base.mvp.model.db.greendao.MovieCollectDao;
import com.hbird.base.mvp.model.db.greendao.WaterOrderCollectDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig waterOrderBeanDaoConfig;
    private final DaoConfig hbirdIncomeTypeDaoConfig;
    private final DaoConfig hbirdSpendTypeDaoConfig;
    private final DaoConfig hbirdUserCommTypePriorityDaoConfig;
    private final DaoConfig hbirdUserCommUseIncomeDaoConfig;
    private final DaoConfig hbirdUserCommUseSpendDaoConfig;
    private final DaoConfig movieCollectDaoConfig;
    private final DaoConfig waterOrderCollectDaoConfig;

    private final WaterOrderBeanDao waterOrderBeanDao;
    private final HbirdIncomeTypeDao hbirdIncomeTypeDao;
    private final HbirdSpendTypeDao hbirdSpendTypeDao;
    private final HbirdUserCommTypePriorityDao hbirdUserCommTypePriorityDao;
    private final HbirdUserCommUseIncomeDao hbirdUserCommUseIncomeDao;
    private final HbirdUserCommUseSpendDao hbirdUserCommUseSpendDao;
    private final MovieCollectDao movieCollectDao;
    private final WaterOrderCollectDao waterOrderCollectDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        waterOrderBeanDaoConfig = daoConfigMap.get(WaterOrderBeanDao.class).clone();
        waterOrderBeanDaoConfig.initIdentityScope(type);

        hbirdIncomeTypeDaoConfig = daoConfigMap.get(HbirdIncomeTypeDao.class).clone();
        hbirdIncomeTypeDaoConfig.initIdentityScope(type);

        hbirdSpendTypeDaoConfig = daoConfigMap.get(HbirdSpendTypeDao.class).clone();
        hbirdSpendTypeDaoConfig.initIdentityScope(type);

        hbirdUserCommTypePriorityDaoConfig = daoConfigMap.get(HbirdUserCommTypePriorityDao.class).clone();
        hbirdUserCommTypePriorityDaoConfig.initIdentityScope(type);

        hbirdUserCommUseIncomeDaoConfig = daoConfigMap.get(HbirdUserCommUseIncomeDao.class).clone();
        hbirdUserCommUseIncomeDaoConfig.initIdentityScope(type);

        hbirdUserCommUseSpendDaoConfig = daoConfigMap.get(HbirdUserCommUseSpendDao.class).clone();
        hbirdUserCommUseSpendDaoConfig.initIdentityScope(type);

        movieCollectDaoConfig = daoConfigMap.get(MovieCollectDao.class).clone();
        movieCollectDaoConfig.initIdentityScope(type);

        waterOrderCollectDaoConfig = daoConfigMap.get(WaterOrderCollectDao.class).clone();
        waterOrderCollectDaoConfig.initIdentityScope(type);

        waterOrderBeanDao = new WaterOrderBeanDao(waterOrderBeanDaoConfig, this);
        hbirdIncomeTypeDao = new HbirdIncomeTypeDao(hbirdIncomeTypeDaoConfig, this);
        hbirdSpendTypeDao = new HbirdSpendTypeDao(hbirdSpendTypeDaoConfig, this);
        hbirdUserCommTypePriorityDao = new HbirdUserCommTypePriorityDao(hbirdUserCommTypePriorityDaoConfig, this);
        hbirdUserCommUseIncomeDao = new HbirdUserCommUseIncomeDao(hbirdUserCommUseIncomeDaoConfig, this);
        hbirdUserCommUseSpendDao = new HbirdUserCommUseSpendDao(hbirdUserCommUseSpendDaoConfig, this);
        movieCollectDao = new MovieCollectDao(movieCollectDaoConfig, this);
        waterOrderCollectDao = new WaterOrderCollectDao(waterOrderCollectDaoConfig, this);

        registerDao(WaterOrderBean.class, waterOrderBeanDao);
        registerDao(HbirdIncomeType.class, hbirdIncomeTypeDao);
        registerDao(HbirdSpendType.class, hbirdSpendTypeDao);
        registerDao(HbirdUserCommTypePriority.class, hbirdUserCommTypePriorityDao);
        registerDao(HbirdUserCommUseIncome.class, hbirdUserCommUseIncomeDao);
        registerDao(HbirdUserCommUseSpend.class, hbirdUserCommUseSpendDao);
        registerDao(MovieCollect.class, movieCollectDao);
        registerDao(WaterOrderCollect.class, waterOrderCollectDao);
    }
    
    public void clear() {
        waterOrderBeanDaoConfig.clearIdentityScope();
        hbirdIncomeTypeDaoConfig.clearIdentityScope();
        hbirdSpendTypeDaoConfig.clearIdentityScope();
        hbirdUserCommTypePriorityDaoConfig.clearIdentityScope();
        hbirdUserCommUseIncomeDaoConfig.clearIdentityScope();
        hbirdUserCommUseSpendDaoConfig.clearIdentityScope();
        movieCollectDaoConfig.clearIdentityScope();
        waterOrderCollectDaoConfig.clearIdentityScope();
    }

    public WaterOrderBeanDao getWaterOrderBeanDao() {
        return waterOrderBeanDao;
    }

    public HbirdIncomeTypeDao getHbirdIncomeTypeDao() {
        return hbirdIncomeTypeDao;
    }

    public HbirdSpendTypeDao getHbirdSpendTypeDao() {
        return hbirdSpendTypeDao;
    }

    public HbirdUserCommTypePriorityDao getHbirdUserCommTypePriorityDao() {
        return hbirdUserCommTypePriorityDao;
    }

    public HbirdUserCommUseIncomeDao getHbirdUserCommUseIncomeDao() {
        return hbirdUserCommUseIncomeDao;
    }

    public HbirdUserCommUseSpendDao getHbirdUserCommUseSpendDao() {
        return hbirdUserCommUseSpendDao;
    }

    public MovieCollectDao getMovieCollectDao() {
        return movieCollectDao;
    }

    public WaterOrderCollectDao getWaterOrderCollectDao() {
        return waterOrderCollectDao;
    }

}
